#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-war-plugin
Version  : 2.6
Release  : 1
URL      : https://github.com/apache/maven-war-plugin/archive/maven-war-plugin-2.6.tar.gz
Source0  : https://github.com/apache/maven-war-plugin/archive/maven-war-plugin-2.6.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.6/maven-war-plugin-2.6.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.6/maven-war-plugin-2.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
